id: I2F2D6E3A
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T23:51:28.795468'
last_modified: '2022-06-18T23:51:28.795482'
parser: null
source_metadata:
  title: Hevajra exposition by bSod nams rtse mo (1142-1182), block print, colophon
    excerpt
  author: སློབ་དཔོན་བསོད་ནམས་རྩེ་མོ།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2015-07-16);
    revised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/960
  bases:
    6d1b:
      title: Hevajra exposition by bSod nams rtse mo (1142-1182), block print, colophon
        excerpt
      order: 1
      base_file: 6d1b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
